In [1]:
import numpy as np

# numpy array

In [2]:
listem = [ 20,30,40]

In [3]:
np.array(listem)

array([20, 30, 40])

In [4]:
matrixlistesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixlistesi[1][0]

20

In [7]:
np.array(matrixlistesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace

In [25]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [26]:
#rakamları esit dağitır sıfeırdan 20 ye kadar
#5 tane rakam getir araları eşit olsun demek


# eye

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random

In [34]:
np.random.randn(4)

array([ 0.18310224,  1.99185032,  0.14047627, -0.1414304 ])

In [35]:
np.random.randn(4,4)

array([[ 0.2491035 ,  0.45624952,  0.51038696, -1.09275091],
       [-1.83432612,  1.03725717,  0.95516374, -0.35625594],
       [ 0.52400362, -0.69518116, -0.70177574, -1.81042875],
       [-0.44496472, -0.02884875,  1.18787975, -0.7913219 ]])

In [38]:
np.random.randint(1,10)

8

In [50]:
np.random.randint(1,100,10)

array([54, 42, 84, 39, 29, 59, 63,  8, 76, 24])

In [51]:
dizi = np.random.randint(1,100,20)

In [52]:
dizi

array([37, 16,  1, 77, 29, 26, 12, 68, 32, 50, 84, 30, 20, 20, 75, 47, 25,
       76, 80, 70])

# numpy dizi methotları

In [53]:
dizi.reshape(4,5)

array([[37, 16,  1, 77, 29],
       [26, 12, 68, 32, 50],
       [84, 30, 20, 20, 75],
       [47, 25, 76, 80, 70]])

In [54]:
dizi.max()

84

In [55]:
dizi.min()

1

In [57]:
dizi.argmax()

10

In [58]:
dizi.argmin()

2

In [61]:
reshapedizi = dizi.reshape(5,4)

In [62]:
reshapedizi.shape

(5, 4)