In [1]:
import numpy as np

In [2]:
dizi = np.arange(0,15)

In [5]:
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
dizi[5]

5

In [7]:
dizi[3:8]

array([3, 4, 5, 6, 7])

In [10]:
dizi[3:8] = -5

In [11]:
dizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [12]:
baskadizi= np.arange(0,24)

In [14]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
kesilendizi = baskadizi[3:11]

In [20]:
kesilendizi

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
kesilendizi[:] = 400

In [23]:
kesilendizi

array([400, 400, 400, 400, 400, 400, 400, 400])

In [24]:
baskadizi

array([  0,   1,   2, 400, 400, 400, 400, 400, 400, 400, 400,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# matrix

In [25]:
liste =[[10,20,30],[20,30,40],[40,50,60]]

In [26]:
matrixdizi = np.array(liste)

In [27]:
matrixdizi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [28]:
matrixdizi[0]

array([10, 20, 30])

In [29]:
matrixdizi[1][2]

40

In [30]:
matrixdizi[1,2]

40

In [31]:
matrixdizi[1:,2]

array([40, 60])

In [32]:
matrixdizi[0:,2]

array([30, 40, 60])